/*
 * jerror.c
 *
 * Copyright (C) 1991-1994, Thomas G. Lane.
 * This file is part of the Independent JPEG Group's software.
 * For conditions of distribution and use, see the accompanying README file.
 *
 * This file contains simple error-reporting and trace-message routines.
 * These are suitable for Unix-like systems and others where writing to
 * stderr is the right thing to do.  Many applications will want to replace
 * some or all of these routines.
 *
 * These routines are used by both the compression and decompression code.
 */

use core::ffi::{c_char, c_int};
use std::ptr;

/* this is not a core library module, so it doesn't define JPEG_INTERNALS */

/* External JPEG library types */
extern "C" {
    pub type j_common_ptr;

    /* Error handler object */
    pub struct jpeg_error_mgr {
        /* Error exit handler: does not return to caller */
        pub error_exit: extern "C" fn(cinfo: *mut j_common_ptr),
        /* Conditionally emit a trace or warning message */
        pub emit_message: extern "C" fn(cinfo: *mut j_common_ptr, msg_level: c_int),
        /* Routine that actually outputs a trace or error message */
        pub output_message: extern "C" fn(cinfo: *mut j_common_ptr),
        /* Format a message string for the most recent JPEG error or message */
        pub format_message: extern "C" fn(cinfo: *mut j_common_ptr, buffer: *mut c_char),
        /* Reset error state variables at start of a new image */
        pub reset_error_mgr: extern "C" fn(cinfo: *mut j_common_ptr),

        /* The message ID code and any parameters are saved here.
         * A message can have one string parameter or up to 8 int parameters.
         */
        pub msg_code: c_int,
        pub msg_parm: jpeg_error_parm_u,

        /* Standard state variables for error facility */

        /* max msg_level that will be displayed */
        pub trace_level: c_int,

        /* For recoverable corrupt-data errors, we emit a warning message,
         * but keep going unless emit_message chooses to abort.  emit_message
         * should count warnings in num_warnings.  The surrounding application
         * can check for bad data by seeing if num_warnings is nonzero at the
         * end of processing.
         */
        /* number of corrupt-data warnings */
        pub num_warnings: c_int,

        /* These fields point to the table(s) of error message strings.
         * An application can change the table pointer to switch to a different
         * message list (typically, to change the language in which errors are
         * reported).  Some applications may wish to add additional error codes
         * that will be handled by the JPEG library error mechanism; the second
         * table pointer is used for this purpose.
         *
         * First table includes all errors generated by JPEG library itself.
         * Error code 0 is reserved for a "no such error string" message.
         */
        /* Library errors */
        pub jpeg_message_table: *const *const c_char,
        /* Table contains strings 0..last_jpeg_message */
        pub last_jpeg_message: c_int,
        /* Second table can be added by application (see cjpeg/djpeg for example).
         * It contains strings numbered first_addon_message..last_addon_message.
         */
        /* Non-library errors */
        pub addon_message_table: *const *const c_char,
        /* code for first string in addon table */
        pub first_addon_message: c_int,
        /* code for last string in addon table */
        pub last_addon_message: c_int,
    }

    #[repr(C)]
    pub union jpeg_error_parm_u {
        pub i: [c_int; 8],
        pub s: [c_char; 80],
    }

    /* External JPEG library functions */
    pub fn jpeg_destroy(cinfo: *mut j_common_ptr);
}

/* Game engine functions */
extern "C" {
    fn Com_Error(level: c_int, format: *const c_char, ...);
    fn Com_Printf(format: *const c_char, ...);
}

/* recommended size of format_message buffer */
const JMSG_LENGTH_MAX: usize = 200;

/*
 * Create the message string table.
 * We do this from the master message list in jerror.h by re-reading
 * jerror.h with a suitable definition for macro JMESSAGE.
 * The message table is made an external symbol just in case any applications
 * want to refer to it directly.
 */

pub static jpeg_std_message_table: [*const c_char; 135] = [
    b"Bogus message code %d\0".as_ptr() as *const c_char, /* Must be first entry! */
    /* For maintenance convenience, list is alphabetical by message code name */
    b"Sorry, there are legal restrictions on arithmetic coding\0".as_ptr() as *const c_char,
    b"ALIGN_TYPE is wrong, please fix\0".as_ptr() as *const c_char,
    b"MAX_ALLOC_CHUNK is wrong, please fix\0".as_ptr() as *const c_char,
    b"Bogus buffer control mode\0".as_ptr() as *const c_char,
    b"Invalid component ID %d in SOS\0".as_ptr() as *const c_char,
    b"IDCT output block size %d not supported\0".as_ptr() as *const c_char,
    b"Bogus input colorspace\0".as_ptr() as *const c_char,
    b"Bogus JPEG colorspace\0".as_ptr() as *const c_char,
    b"Bogus marker length\0".as_ptr() as *const c_char,
    b"Sampling factors too large for interleaved scan\0".as_ptr() as *const c_char,
    b"Invalid memory pool code %d\0".as_ptr() as *const c_char,
    b"Unsupported JPEG data precision %d\0".as_ptr() as *const c_char,
    b"Invalid progressive parameters Ss=%d Se=%d Ah=%d Al=%d\0".as_ptr() as *const c_char,
    b"Invalid progressive parameters at scan script entry %d\0".as_ptr() as *const c_char,
    b"Bogus sampling factors\0".as_ptr() as *const c_char,
    b"Invalid scan script at entry %d\0".as_ptr() as *const c_char,
    b"Improper call to JPEG library in state %d\0".as_ptr() as *const c_char,
    b"Bogus virtual array access\0".as_ptr() as *const c_char,
    b"Buffer passed to JPEG library is too small\0".as_ptr() as *const c_char,
    b"Suspension not allowed here\0".as_ptr() as *const c_char,
    b"CCIR601 sampling not implemented yet\0".as_ptr() as *const c_char,
    b"Too many color components: %d, max %d\0".as_ptr() as *const c_char,
    b"Unsupported color conversion request\0".as_ptr() as *const c_char,
    b"Bogus DAC index %d\0".as_ptr() as *const c_char,
    b"Bogus DAC value 0x%x\0".as_ptr() as *const c_char,
    b"Bogus DHT counts\0".as_ptr() as *const c_char,
    b"Bogus DHT index %d\0".as_ptr() as *const c_char,
    b"Bogus DQT index %d\0".as_ptr() as *const c_char,
    b"Empty JPEG image (DNL not supported)\0".as_ptr() as *const c_char,
    b"Read from EMS failed\0".as_ptr() as *const c_char,
    b"Write to EMS failed\0".as_ptr() as *const c_char,
    b"Didn't expect more than one scan\0".as_ptr() as *const c_char,
    b"Input file read error\0".as_ptr() as *const c_char,
    b"Output file write error --- out of disk space?\0".as_ptr() as *const c_char,
    b"Fractional sampling not implemented yet\0".as_ptr() as *const c_char,
    b"Huffman code size table overflow\0".as_ptr() as *const c_char,
    b"Missing Huffman code table entry\0".as_ptr() as *const c_char,
    b"Maximum supported image dimension is %u pixels\0".as_ptr() as *const c_char,
    b"Empty input file\0".as_ptr() as *const c_char,
    b"Premature end of input file\0".as_ptr() as *const c_char,
    b"Cannot transcode due to multiple use of quantization table %d\0".as_ptr() as *const c_char,
    b"Scan script does not transmit all data\0".as_ptr() as *const c_char,
    b"Invalid color quantization mode change\0".as_ptr() as *const c_char,
    b"Not implemented yet\0".as_ptr() as *const c_char,
    b"Requested feature was omitted at compile time\0".as_ptr() as *const c_char,
    b"Backing store not supported\0".as_ptr() as *const c_char,
    b"Huffman table 0x%02x was not defined\0".as_ptr() as *const c_char,
    b"JPEG datastream contains no image\0".as_ptr() as *const c_char,
    b"Quantization table 0x%02x was not defined\0".as_ptr() as *const c_char,
    b"Not a JPEG file: starts with 0x%02x 0x%02x\0".as_ptr() as *const c_char,
    b"Insufficient memory (case %d)\0".as_ptr() as *const c_char,
    b"Cannot quantize more than %d color components\0".as_ptr() as *const c_char,
    b"Cannot quantize to fewer than %d colors\0".as_ptr() as *const c_char,
    b"Cannot quantize to more than %d colors\0".as_ptr() as *const c_char,
    b"Invalid JPEG file structure: two SOF markers\0".as_ptr() as *const c_char,
    b"Invalid JPEG file structure: missing SOS marker\0".as_ptr() as *const c_char,
    b"Unsupported JPEG process: SOF type 0x%02x\0".as_ptr() as *const c_char,
    b"Invalid JPEG file structure: two SOI markers\0".as_ptr() as *const c_char,
    b"Invalid JPEG file structure: SOS before SOF\0".as_ptr() as *const c_char,
    b"Failed to create temporary file %s\0".as_ptr() as *const c_char,
    b"Read failed on temporary file\0".as_ptr() as *const c_char,
    b"Seek failed on temporary file\0".as_ptr() as *const c_char,
    b"Write failed on temporary file --- out of disk space?\0".as_ptr() as *const c_char,
    b"Application transferred too few scanlines\0".as_ptr() as *const c_char,
    b"Unsupported marker type 0x%02x\0".as_ptr() as *const c_char,
    b"Virtual array controller messed up\0".as_ptr() as *const c_char,
    b"Image too wide for this implementation\0".as_ptr() as *const c_char,
    b"Read from XMS failed\0".as_ptr() as *const c_char,
    b"Write to XMS failed\0".as_ptr() as *const c_char,
    b"Copyright (C) 1995, Thomas G. Lane\0".as_ptr() as *const c_char,
    b"6  2-Aug-95\0".as_ptr() as *const c_char,
    b"Caution: quantization tables are too coarse for baseline JPEG\0".as_ptr() as *const c_char,
    b"Adobe APP14 marker: version %d, flags 0x%04x 0x%04x, transform %d\0".as_ptr() as *const c_char,
    b"Unknown APP0 marker (not JFIF), length %u\0".as_ptr() as *const c_char,
    b"Unknown APP14 marker (not Adobe), length %u\0".as_ptr() as *const c_char,
    b"Define Arithmetic Table 0x%02x: 0x%02x\0".as_ptr() as *const c_char,
    b"Define Huffman Table 0x%02x\0".as_ptr() as *const c_char,
    b"Define Quantization Table %d  precision %d\0".as_ptr() as *const c_char,
    b"Define Restart Interval %u\0".as_ptr() as *const c_char,
    b"Freed EMS handle %u\0".as_ptr() as *const c_char,
    b"Obtained EMS handle %u\0".as_ptr() as *const c_char,
    b"End Of Image\0".as_ptr() as *const c_char,
    b"        %3d %3d %3d %3d %3d %3d %3d %3d\0".as_ptr() as *const c_char,
    b"JFIF APP0 marker, density %dx%d  %d\0".as_ptr() as *const c_char,
    b"Warning: thumbnail image size does not match data length %u\0".as_ptr() as *const c_char,
    b"Unknown JFIF minor revision number %d.%02d\0".as_ptr() as *const c_char,
    b"    with %d x %d thumbnail image\0".as_ptr() as *const c_char,
    b"Skipping marker 0x%02x, length %u\0".as_ptr() as *const c_char,
    b"Unexpected marker 0x%02x\0".as_ptr() as *const c_char,
    b"        %4u %4u %4u %4u %4u %4u %4u %4u\0".as_ptr() as *const c_char,
    b"Quantizing to %d = %d*%d*%d colors\0".as_ptr() as *const c_char,
    b"Quantizing to %d colors\0".as_ptr() as *const c_char,
    b"Selected %d colors for quantization\0".as_ptr() as *const c_char,
    b"At marker 0x%02x, recovery action %d\0".as_ptr() as *const c_char,
    b"RST%d\0".as_ptr() as *const c_char,
    b"Smoothing not supported with nonstandard sampling ratios\0".as_ptr() as *const c_char,
    b"Start Of Frame 0x%02x: width=%u, height=%u, components=%d\0".as_ptr() as *const c_char,
    b"    Component %d: %dhx%dv q=%d\0".as_ptr() as *const c_char,
    b"Start of Image\0".as_ptr() as *const c_char,
    b"Start Of Scan: %d components\0".as_ptr() as *const c_char,
    b"    Component %d: dc=%d ac=%d\0".as_ptr() as *const c_char,
    b"  Ss=%d, Se=%d, Ah=%d, Al=%d\0".as_ptr() as *const c_char,
    b"Closed temporary file %s\0".as_ptr() as *const c_char,
    b"Opened temporary file %s\0".as_ptr() as *const c_char,
    b"Unrecognized component IDs %d %d %d, assuming YCbCr\0".as_ptr() as *const c_char,
    b"Freed XMS handle %u\0".as_ptr() as *const c_char,
    b"Obtained XMS handle %u\0".as_ptr() as *const c_char,
    b"Unknown Adobe color transform code %d\0".as_ptr() as *const c_char,
    b"Inconsistent progression sequence for component %d coefficient %d\0".as_ptr() as *const c_char,
    b"Corrupt JPEG data: %u extraneous bytes before marker 0x%02x\0".as_ptr() as *const c_char,
    b"Corrupt JPEG data: premature end of data segment\0".as_ptr() as *const c_char,
    b"Corrupt JPEG data: bad Huffman code\0".as_ptr() as *const c_char,
    b"Warning: unknown JFIF revision number %d.%02d\0".as_ptr() as *const c_char,
    b"Premature end of JPEG file\0".as_ptr() as *const c_char,
    b"Corrupt JPEG data: found marker 0x%02x instead of RST%d\0".as_ptr() as *const c_char,
    b"Invalid SOS parameters for sequential JPEG\0".as_ptr() as *const c_char,
    b"Application transferred too many scanlines\0".as_ptr() as *const c_char,
];

/*
 * Error exit handler: must not return to caller.
 *
 * Applications may override this if they want to get control back after
 * an error.  Typically one would longjmp somewhere instead of exiting.
 * The setjmp buffer can be made a private field within an expanded error
 * handler object.  Note that the info needed to generate an error message
 * is stored in the error object, so you can generate the message now or
 * later, at your convenience.
 * You should make sure that the JPEG object is cleaned up (with jpeg_abort
 * or jpeg_destroy) at some point.
 */

extern "C" fn error_exit(cinfo: *mut j_common_ptr) {
    let mut buffer: [u8; JMSG_LENGTH_MAX] = [0; JMSG_LENGTH_MAX];

    unsafe {
        /* Create the message */
        let err = (*(*cinfo).err);
        (err.format_message)(cinfo, buffer.as_mut_ptr() as *mut c_char);

        /* Let the memory manager delete any temp files before we die */
        jpeg_destroy(cinfo);

        Com_Error(
            2, /* ERR_FATAL */
            b"%s\n".as_ptr() as *const c_char,
            buffer.as_ptr() as *const c_char,
        );
    }
}

/*
 * Actual output of an error or trace message.
 * Applications may override this method to send JPEG messages somewhere
 * other than stderr.
 */

extern "C" fn output_message(cinfo: *mut j_common_ptr) {
    let mut buffer: [u8; JMSG_LENGTH_MAX] = [0; JMSG_LENGTH_MAX];

    unsafe {
        /* Create the message */
        let err = (*(*cinfo).err);
        (err.format_message)(cinfo, buffer.as_mut_ptr() as *mut c_char);

        /* Send it to stderr, adding a newline */
        Com_Printf(
            b"%s\n".as_ptr() as *const c_char,
            buffer.as_ptr() as *const c_char,
        );
    }
}

/*
 * Decide whether to emit a trace or warning message.
 * msg_level is one of:
 *   -1: recoverable corrupt-data warning, may want to abort.
 *    0: important advisory messages (always display to user).
 *    1: first level of tracing detail.
 *    2,3,...: successively more detailed tracing messages.
 * An application might override this method if it wanted to abort on warnings
 * or change the policy about which messages to display.
 */

extern "C" fn emit_message(cinfo: *mut j_common_ptr, msg_level: c_int) {
    unsafe {
        let err = &mut *(*cinfo).err;

        if msg_level < 0 {
            /* It's a warning message.  Since corrupt files may generate many warnings,
             * the policy implemented here is to show only the first warning,
             * unless trace_level >= 3.
             */
            if err.num_warnings == 0 || err.trace_level >= 3 {
                (err.output_message)(cinfo);
            }
            /* Always count warnings in num_warnings. */
            err.num_warnings += 1;
        } else {
            /* It's a trace message.  Show it if trace_level >= msg_level. */
            if err.trace_level >= msg_level {
                (err.output_message)(cinfo);
            }
        }
    }
}

/*
 * Format a message string for the most recent JPEG error or message.
 * The message is stored into buffer, which should be at least JMSG_LENGTH_MAX
 * characters.  Note that no '\n' character is added to the string.
 * Few applications should need to override this method.
 */

extern "C" fn format_message(cinfo: *mut j_common_ptr, buffer: *mut c_char) {
    unsafe {
        let err = &mut *(*cinfo).err;
        let msg_code = err.msg_code;
        let mut msgtext: *const c_char = ptr::null();
        let mut msgptr: *const c_char;
        let mut ch: c_char;
        let mut isstring: bool = false;

        /* Look up message string in proper table */
        if msg_code > 0 && msg_code <= err.last_jpeg_message {
            msgtext = *err.jpeg_message_table.offset(msg_code as isize);
        } else if !err.addon_message_table.is_null()
            && msg_code >= err.first_addon_message
            && msg_code <= err.last_addon_message
        {
            msgtext = *err.addon_message_table.offset((msg_code - err.first_addon_message) as isize);
        }

        /* Defend against bogus message number */
        if msgtext.is_null() {
            err.msg_parm.i[0] = msg_code;
            msgtext = *err.jpeg_message_table.offset(0);
        }

        /* Check for string parameter, as indicated by %s in the message text */
        isstring = false;
        msgptr = msgtext;
        loop {
            ch = *msgptr;
            msgptr = msgptr.offset(1);
            if ch == 0 {
                break;
            }
            if ch == b'%' as c_char {
                if *msgptr == b's' as c_char {
                    isstring = true;
                }
                break;
            }
        }

        /* Format the message into the passed buffer */
        if isstring {
            sprintf(buffer, msgtext, err.msg_parm.s.as_ptr());
        } else {
            sprintf(
                buffer,
                msgtext,
                err.msg_parm.i[0],
                err.msg_parm.i[1],
                err.msg_parm.i[2],
                err.msg_parm.i[3],
                err.msg_parm.i[4],
                err.msg_parm.i[5],
                err.msg_parm.i[6],
                err.msg_parm.i[7],
            );
        }
    }
}

/*
 * Reset error state variables at start of a new image.
 * This is called during compression startup to reset trace/error
 * processing to default state, without losing any application-specific
 * method pointers.  An application might possibly want to override
 * this method if it has additional error processing state.
 */

extern "C" fn reset_error_mgr(cinfo: *mut j_common_ptr) {
    unsafe {
        (*(*cinfo).err).num_warnings = 0;
        /* trace_level is not reset since it is an application-supplied parameter */
        (*(*cinfo).err).msg_code = 0; /* may be useful as a flag for "no error" */
    }
}

/*
 * Fill in the standard error-handling methods in a jpeg_error_mgr object.
 * Typical call is:
 *	struct jpeg_compress_struct cinfo;
 *	struct jpeg_error_mgr err;
 *
 *	cinfo.err = jpeg_std_error(&err);
 * after which the application may override some of the methods.
 */

#[no_mangle]
pub extern "C" fn jpeg_std_error(err: *mut jpeg_error_mgr) -> *mut jpeg_error_mgr {
    unsafe {
        (*err).error_exit = error_exit;
        (*err).emit_message = emit_message;
        (*err).output_message = output_message;
        (*err).format_message = format_message;
        (*err).reset_error_mgr = reset_error_mgr;

        (*err).trace_level = 0; /* default = no tracing */
        (*err).num_warnings = 0; /* no warnings emitted yet */
        (*err).msg_code = 0; /* may be useful as a flag for "no error" */

        /* Initialize message table pointers */
        (*err).jpeg_message_table = jpeg_std_message_table.as_ptr() as *const *const c_char;
        (*err).last_jpeg_message = (jpeg_std_message_table.len() as c_int) - 2; /* excluding NULL */

        (*err).addon_message_table = ptr::null();
        (*err).first_addon_message = 0; /* for safety */
        (*err).last_addon_message = 0;
    }

    err
}

/* sprintf stub - declared as extern since it's a libc function */
extern "C" {
    fn sprintf(s: *mut c_char, format: *const c_char, ...) -> c_int;
}
