// Filename: mdx_format.h
//
// DO NOT UPDATE THIS FILE IN ANY WAY WHATSOEVER WITHOUT TELLING ME (-Ste),
//	BECAUSE THE MASTER COPY IS IN A DIFFERENT SOURCESAFE DATABASE AND WILL
//	JUST GET PASTED OVER THIS ONE WHENEVER I CHANGE IT.
//
//
//
// MDX file format (typically uses file extension GLX for mesh, and GLA for anim/skeleton file)
//
// Notes:
//
//	- All offset fields are relative to the address of the structure they occur in
//	- So far, the only external symbol needed is MAX_QPATH, plus the typedefs for vec3_t, vec2_t etc

use core::ffi::c_int;

pub const MDXM_IDENT: c_int = (('M' as c_int) << 24) + (('G' as c_int) << 16) + (('L' as c_int) << 8) + ('2' as c_int);
pub const MDXA_IDENT: c_int = (('A' as c_int) << 24) + (('G' as c_int) << 16) + (('L' as c_int) << 8) + ('2' as c_int);

pub const MAX_TAGNAME_BYTES: usize = 32;	// matches MDR, can be changed if nec.

//
// normal version numbers...
//
pub const MDXM_VERSION: c_int = 6;
pub const MDXA_VERSION: c_int = 6;

// (Note that since there is now a "<modelname>_info.txt" file written out by carcass any changes made in here that
//		introduce new data should also be reflected in the info-output)

// 32 bit-flags for ghoul2 bone properties...  (all undefined fields will be blank)
//
pub const G2BONEFLAG_ALWAYSXFORM: u32 = 0x00000001;

// same thing but for surfaces...  (Carcass will only generate 1st 2 flags, others are ingame
//
pub const G2SURFACEFLAG_ISBOLT: u32 = 0x00000001;
pub const G2SURFACEFLAG_OFF: u32 = 0x00000002;	// saves strcmp()ing for "_off" in surface names
pub const G2SURFACEFLAG_SPARE0: u32 = 0x00000004;	// future-expansion fields, saves invalidating models if we add more
pub const G2SURFACEFLAG_SPARE1: u32 = 0x00000008;	//
pub const G2SURFACEFLAG_SPARE2: u32 = 0x00000010;	//
pub const G2SURFACEFLAG_SPARE3: u32 = 0x00000020;	//
pub const G2SURFACEFLAG_SPARE4: u32 = 0x00000040;	//
pub const G2SURFACEFLAG_SPARE5: u32 = 0x00000080;	//
//
pub const G2SURFACEFLAG_NODESCENDANTS: u32 = 0x00000100;	// ingame-stuff, never generated by Carcass....
pub const G2SURFACEFLAG_GENERATED: u32 = 0x00000200;	//



// triangle side-ordering stuff for tags...
//
pub const iG2_TRISIDE_MIDDLE: c_int = 1;
pub const iG2_TRISIDE_LONGEST: c_int = 0;
pub const iG2_TRISIDE_SHORTEST: c_int = 2;

pub const fG2_BONEWEIGHT_RECIPROCAL_MULT: f32 = 1.0f32 / 1023.0f32;
pub const iG2_BITS_PER_BONEREF: c_int = 5;
pub const iMAX_G2_BONEREFS_PER_SURFACE: c_int = 1 << iG2_BITS_PER_BONEREF;	// (32)
pub const iMAX_G2_BONEWEIGHTS_PER_VERT: c_int = 4;	// can't just be blindly increased, affects cache size etc

pub const iG2_BONEWEIGHT_TOPBITS_SHIFT: c_int = (iG2_BITS_PER_BONEREF * iMAX_G2_BONEWEIGHTS_PER_VERT) - 8;	// 8 bits because of 8 in the BoneWeight[] array entry
pub const iG2_BONEWEIGHT_TOPBITS_AND: c_int = 0x300;	// 2 bits, giving 10 total, or 10 bits, for 1023/1024 above


pub const sDEFAULT_GLA_NAME: &[u8] = b"*default";	// used when making special simple ghoul2 models, usually from MD3 files


////////////////////////////////////
//
// these structs are defined here purely because of structure dependancy order...
//
// (commented out C++ section omitted - mdxmWeight_t and mdxaCompBone_t)

#[repr(C)]
pub struct mdxaCompQuatBone_t {
	pub Comp: [u8; 14],

	// I'm defining this '<' operator so this struct can be used as an STL <map> key...
	// (C++ operator< omitted - Rust doesn't need it for this port)
}


#[repr(C)]
pub struct mdxaBone_t {
	pub matrix: [[f32; 4]; 3],
}


////////////////////////////////////




// mdxHeader_t  - this contains the header for the file, with sanity checking and version checking, plus number of lod's to be expected
//
#[repr(C)]
pub struct mdxmHeader_t {
	//
	// ( first 3 fields are same format as MD3/MDR so we can apply easy model-format-type checks )
	//
	pub ident: c_int,				// "IDP3" = MD3, "RDM5" = MDR, "2LGM"(GL2 Mesh) = MDX   (cruddy char order I know, but I'm following what was there in other versions)
	pub version: c_int,			// 1,2,3 etc as per format revision
	pub name: [u8; 260],	// model name (eg "models/players/marine.glm")	// note: extension supplied // FIXME: MAX_QPATH
	pub animName: [u8; 260],// name of animation file this mesh requires	// note: extension missing // FIXME: MAX_QPATH
	pub animIndex: c_int,			// filled in by game (carcass defaults it to 0)

	pub numBones: c_int,			// (for ingame version-checks only, ensure we don't ref more bones than skel file has)

	pub numLODs: c_int,
	pub ofsLODs: c_int,

	pub numSurfaces: c_int,		// now that surfaces are drawn hierarchically, we have same # per LOD
	pub ofsSurfHierarchy: c_int,

	pub ofsEnd: c_int,				// EOF, which of course gives overall file size
}


// for each surface (doesn't actually need a struct for this, just makes source clearer)
// {
#[repr(C)]
pub struct mdxmHierarchyOffsets_t {
	pub offsets: [c_int; 1],		// variable sized (mdxmHeader_t->numSurfaces), each offset points to a mdxmSurfHierarchy_t below
}
// }

// for each surface...	(mdxmHeader_t->numSurfaces)
// {
		// mdxmSurfHierarchy_t - contains hierarchical info for surfaces...

#[repr(C)]
pub struct mdxmSurfHierarchy_t {
	pub name: [u8; 260],	// FIXME: MAX_QPATH
	pub flags: u32,
	pub shader: [u8; 260],	// FIXME: MAX_QPATH
	pub shaderIndex: c_int,		// for in-game use (carcass defaults to 0)
	pub parentIndex: c_int,		// this points to the index in the file of the parent surface. -1 if null/root
	pub numChildren: c_int,		// number of surfaces which are children of this one
	pub childIndexes: [c_int; 1],	// [mdxmSurfHierarch_t->numChildren] (variable sized)
}	// struct size = (int)( &((mdxmSurfHierarch_t *)0)->childIndexes[ mdxmSurfHierarch_t->numChildren ] );
// }


// for each LOD...  (mdxmHeader_t->numLODs)
// {
		// mdxLOD_t - this contains the header for this LOD. Contains num of surfaces, offset to surfaces and offset to next LOD. Surfaces are shader sorted, so each surface = 1 shader

#[repr(C)]
pub struct mdxmLOD_t {
	// (used to contain numSurface/ofsSurfaces fields, but these are same per LOD level now)
	//
	pub ofsEnd: c_int,				// offset to next LOD
}


#[repr(C)]
pub struct mdxmLODSurfOffset_t {	// added in GLM version 3 for ingame use at Jake's request
	pub offsets: [c_int; 1],		// variable sized (mdxmHeader_t->numSurfaces), each offset points to surfaces below
}


		// for each surface... (mdxmHeader_t->numSurfaces)
		// {
				// mdxSurface_t - reuse of header format containing surface name, number of bones, offset to poly data and number of polys, offset to vertex information, and number of verts. NOTE offsets are relative to this header.

#[repr(C)]
pub struct mdxmSurface_t {
	pub ident: c_int,				// this one field at least should be kept, since the game-engine may switch-case (but currently=0 in carcass)

	pub thisSurfaceIndex: c_int,	// 0...mdxmHeader_t->numSurfaces-1 (because of how ingame renderer works)

	pub ofsHeader: c_int,			// this will be a negative number, pointing back to main header

	pub numVerts: c_int,
	pub ofsVerts: c_int,

	pub numTriangles: c_int,
	pub ofsTriangles: c_int,

	// Bone references are a set of ints representing all the bones
	// present in any vertex weights for this surface.  This is
	// needed because a model may have surfaces that need to be
	// drawn at different sort times, and we don't want to have
	// to re-interpolate all the bones for each surface.
	//
	pub numBoneReferences: c_int,
	pub ofsBoneReferences: c_int,

	pub ofsEnd: c_int,				// next surface follows

}


				// for each triangle...	(mdxmSurface_t->numTriangles)
				// {
						// mdxTriangle_t - contains indexes into verts. One struct entry per poly.

#[repr(C)]
pub struct mdxmTriangle_t {
	pub indexes: [c_int; 3],
}
				// }


				// for each vert... (mdxmSurface_t->numVerts)
				// {
						// mdxVertex_t - this is an array with number of verts from the surface definition as its bounds. It contains normal info, texture coors and number of weightings for this bone
						// (this is now kept at 32 bytes for cache-aligning)
#[repr(C)]
pub struct mdxmVertex_t {
	// Platform conditional: Xbox vs others
	// For non-Xbox: vec3_t normal, vec3_t vertCoords (both [f32; 3])
	pub normal: [f32; 3],
	pub vertCoords: [f32; 3],

	// packed int...
	pub uiNmWeightsAndBoneIndexes: u32,	// 32 bits.  format:
														// 31 & 30:  0..3 (= 1..4) weight count
														// 29 & 28 (spare)
														//	2 bit pairs at 20,22,24,26 are 2-bit overflows from 4 BonWeights below (20=[0], 22=[1]) etc)
														//  5-bits each (iG2_BITS_PER_BONEREF) for boneweights
	// effectively a packed int, each bone weight converted from 0..1 float to 0..255 int...
	//  promote each entry to float and multiply by fG2_BONEWEIGHT_RECIPROCAL_MULT to convert.
	pub BoneWeightings: [u8; 4],	// iMAX_G2_BONEWEIGHTS_PER_VERT = 4

}

				// } vert

// these are convenience functions that I can invoked in code. Do NOT change them (because this is a shared file),
//	but if you want to copy the logic out and use your own versions then fine...
//
#[inline]
pub fn G2_GetVertWeights(pVert: *const mdxmVertex_t) -> c_int {
	let iNumWeights = unsafe { ((*pVert).uiNmWeightsAndBoneIndexes >> 30) + 1 };	// 1..4 count

	iNumWeights as c_int
}

#[inline]
pub fn G2_GetVertBoneIndex(pVert: *const mdxmVertex_t, iWeightNum: c_int) -> c_int {
	let iBoneIndex = unsafe { ((*pVert).uiNmWeightsAndBoneIndexes >> (iG2_BITS_PER_BONEREF * iWeightNum)) & ((1 << iG2_BITS_PER_BONEREF) as u32 - 1) };

	iBoneIndex as c_int
}

#[inline]
pub fn G2_GetVertBoneWeight(pVert: *const mdxmVertex_t, iWeightNum: c_int, fTotalWeight: &mut f32, iNumWeights: c_int) -> f32 {
	let mut fBoneWeight: f32;

	if iWeightNum == iNumWeights - 1 {
		fBoneWeight = 1.0f32 - *fTotalWeight;
	} else {
		let mut iTemp = unsafe { (*pVert).BoneWeightings[iWeightNum as usize] as u32 };
		iTemp |= unsafe { ((*pVert).uiNmWeightsAndBoneIndexes >> (iG2_BONEWEIGHT_TOPBITS_SHIFT + (iWeightNum * 2))) & iG2_BONEWEIGHT_TOPBITS_AND as u32 };

		fBoneWeight = fG2_BONEWEIGHT_RECIPROCAL_MULT * iTemp as f32;
		*fTotalWeight += fBoneWeight;
	}

	fBoneWeight
}
				// for each vert... (mdxmSurface_t->numVerts)  (seperated from mdxmVertex_t struct for cache reasons)
				// {
						// mdxVertex_t - this is an array with number of verts from the surface definition as its bounds. It contains normal info, texture coors and number of weightings for this bone

#[repr(C)]
pub struct mdxmVertexTexCoord_t {
	// Platform conditional: Xbox vs others
	// For non-Xbox: vec2_t texCoords ([f32; 2])
	pub texCoords: [f32; 2],
}

				// } vert


		// } surface
// } LOD



//----------------------------------------------------------------------------
// seperate file here for animation data...
//


// mdxaHeader_t  - this contains the header for the file, with sanity checking and version checking, plus number of lod's to be expected
//
#[repr(C)]
pub struct mdxaHeader_t {
	//
	// ( first 3 fields are same format as MD3/MDR so we can apply easy model-format-type checks )
	//
	pub ident: c_int,				// 	"IDP3" = MD3, "RDM5" = MDR, "2LGA"(GL2 Anim) = MDXA
	pub version: c_int,			// 1,2,3 etc as per format revision
	//
	pub name: [u8; 260],	// GLA name (eg "skeletons/marine")	// note: extension missing // FIXME: MAX_QPATH
	pub fScale: f32,				// will be zero if build before this field was defined, else scale it was built with

	// frames and bones are shared by all levels of detail
	//
	pub numFrames: c_int,
	pub ofsFrames: c_int,			// points at mdxaFrame_t array
	pub numBones: c_int,			// (no offset to these since they're inside the frames array)
	pub ofsCompBonePool: c_int,	// offset to global compressed-bone pool that all frames use
	pub ofsSkel: c_int,			// offset to mdxaSkel_t info

	pub ofsEnd: c_int,				// EOF, which of course gives overall file size

}


// for each bone... (doesn't actually need a struct for this, just makes source clearer)
// {
#[repr(C)]
pub struct mdxaSkelOffsets_t {
	pub offsets: [c_int; 1],		// variable sized (mdxaHeader_t->numBones), each offset points to an mdxaSkel_t below
}
// }



// for each bone...	 (mdxaHeader_t->numBones)
// {
		// mdxaSkel_t - contains hierarchical info only...

#[repr(C)]
pub struct mdxaSkel_t {
	pub name: [u8; 260],	// name of bone // FIXME: MAX_QPATH
	pub flags: u32,
	pub parent: c_int,				// index of bone that is parent to this one, -1 = NULL/root
	pub BasePoseMat: mdxaBone_t,		// base pose
	pub BasePoseMatInv: mdxaBone_t,		// inverse, to save run-time calc
	pub numChildren: c_int,		// number of children bones
	pub children: [c_int; 1],		// [mdxaSkel_t->numChildren] (variable sized)
}	// struct size = (int)( &((mdxaSkel_t *)0)->children[ mdxaSkel_t->numChildren ] );
// }


	// (offset @ mdxaHeader_t->ofsFrames)
	//
	//  array of 3 byte indices here (hey, 25% saving over 4-byte really adds up)...
	//
	//
	// access as follows to get the index for a given <iFrameNum, iBoneNum>
	//
	// (iFrameNum * mdxaHeader_t->numBones * 3) + (iBoneNum * 3)
	//
	//  then read the int at that location and AND it with 0x00FFFFFF. I use the struct below simply for easy searches
#[repr(C)]
pub struct mdxaIndex_t {
	pub iIndex: c_int,	// this struct for pointing purposes, need to and with 0x00FFFFFF to be meaningful
}
	//
	// (note that there's then an alignement-pad here to get the next struct back onto 32-bit alignement)
	//
	// this index then points into the following...


// Compressed-bone pool that all frames use  (mdxaHeader_t->ofsCompBonePool)  (defined at end because size unknown until end)
// for each bone in pool (unknown number, no actual total stored at the moment)...
// {
		// mdxaCompBone_t  (defined at file top because of struct dependancy)
// }

//---------------------------------------------------------------------------
