/**********************************************************************
	Copyright (c) 1997 - 2000 Immersion Corporation

	Permission to use, copy, modify, distribute, and sell this
	software and its documentation may be granted without fee;
	interested parties are encouraged to request permission from
		Immersion Corporation
		801 Fox Lane
		San Jose, CA 95131
		408-467-1900

	IMMERSION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
	INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
	IN NO EVENT SHALL IMMERSION BE LIABLE FOR ANY SPECIAL, INDIRECT OR
	CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
	LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
	NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
	CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

  FILE:		ImmBaseTypes.h

  PURPOSE:	Base Types for Feelit API Foundation Classes

  STARTED:	10/29/97

  NOTES/REVISIONS:
     3/2/99 jrm (Jeff Mallett): Force-->Feel renaming

**********************************************************************/

// Porting note: AFX_IMMBASETYPES_H__135B88C4_4175_11D1_B049_0020AF30269A__INCLUDED_
// Header guard translated from preprocessor to module system

#![allow(non_snake_case)]

// include "FeelitApi.h"
// Porting note: FeelitApi symbols assumed available via FeelitAPI_h module

use crate::code::ff::IFC::FeelitAPI_h::*;

// Version 0x0100 -- IFC10
// Version 0x0101 -- IFC10p Special release: contains CImmProject::DestroyEffect
// Version 0x0110 -- IFC21 (and IFC20?)
#[cfg(not(feature = "IFC_VERSION"))]
pub const IFC_VERSION: u32 = 0x0110;

// #if (IFC_VERSION >= 0x0101)
//  // This means that a user can call delete on a CImmCompoundEffect
//  // object that was allocated through a CImmProject::CreateEffect()
//  // and all will be well.
// #define PROTECT_AGAINST_DELETION
// #endif

// #if (IFC_VERSION >= 0x0110)
pub const IFC_START_DELAY: bool = true;
pub const IFC_EFFECT_CACHING: bool = true;
// #endif

// Add define for DirectInput Device emulating FEELit Device
pub const FEELIT_DEVICETYPE_DIRECTINPUT: i32 = 3;

//================================================================
// TYPE WRAPPERS
//================================================================

//
// IMM --> FEELIT Wrappers
//
pub const IMM_VERSION: u32 = FEELIT_VERSION;

pub const IMM_DEVICETYPE_DEVICE: i32 = FEELIT_DEVICETYPE_DEVICE;
pub const IMM_DEVICETYPE_MOUSE: i32 = FEELIT_DEVICETYPE_MOUSE;
pub const IMM_DEVICETYPE_HID: i32 = FEELIT_DEVICETYPE_HID;
pub const IMM_DEVICETYPE_DIRECTINPUT: i32 = FEELIT_DEVICETYPE_DIRECTINPUT;

pub const IMM_EFFECT: u32 = FEELIT_EFFECT;
pub const LPIMM_EFFECT: u32 = LPFEELIT_EFFECT;
pub const LPCIMM_EFFECT: u32 = LPCFEELIT_EFFECT;

pub const IMM_CONDITION: u32 = FEELIT_CONDITION;
pub const LPIMM_CONDITION: u32 = LPFEELIT_CONDITION;
pub const LPCIMM_CONDITION: u32 = LPCFEELIT_CONDITION;

pub const IMM_CONSTANTFORCE: u32 = FEELIT_CONSTANTFORCE;
pub const LPIMM_CONSTANTFORCE: u32 = LPFEELIT_CONSTANTFORCE;
pub const LPCIMM_CONSTANTFORCE: u32 = LPCFEELIT_CONSTANTFORCE;

pub const IMM_ELLIPSE: u32 = FEELIT_ELLIPSE;
pub const LPIMM_ELLIPSE: u32 = LPFEELIT_ELLIPSE;
pub const LPCIMM_ELLIPSE: u32 = LPCFEELIT_ELLIPSE;

pub const IMM_ENCLOSURE: u32 = FEELIT_ENCLOSURE;
pub const LPIMM_ENCLOSURE: u32 = LPFEELIT_ENCLOSURE;
pub const LPCIMM_ENCLOSURE: u32 = LPCFEELIT_ENCLOSURE;

pub const IMM_PERIODIC: u32 = FEELIT_PERIODIC;
pub const LPIMM_PERIODIC: u32 = LPFEELIT_PERIODIC;
pub const LPCIMM_PERIODIC: u32 = LPCFEELIT_PERIODIC;

pub const IMM_RAMPFORCE: u32 = FEELIT_RAMPFORCE;
pub const LPIMM_RAMPFORCE: u32 = LPFEELIT_RAMPFORCE;
pub const LPCIMM_RAMPFORCE: u32 = LPFEELIT_RAMPFORCE;

pub const IMM_TEXTURE: u32 = FEELIT_TEXTURE;
pub const LPIMM_TEXTURE: u32 = LPFEELIT_TEXTURE;
pub const LPCIMM_TEXTURE: u32 = LPCFEELIT_TEXTURE;

pub const IMM_ENVELOPE: u32 = FEELIT_ENVELOPE;
pub const LPIMM_ENVELOPE: u32 = LPFEELIT_ENVELOPE;
pub const LPCIMM_ENVELOPE: u32 = LPCFEELIT_ENVELOPE;

pub const LPIIMM_API: u32 = LPIFEELIT;
pub const LPIIMM_EFFECT: u32 = LPIFEELIT_EFFECT;
pub const LPIIMM_DEVICE: u32 = LPIFEELIT_DEVICE;

pub const IMM_CUSTOMFORCE: u32 = FEELIT_CUSTOMFORCE;
pub const LPIMM_CUSTOMFORCE: u32 = LPFEELIT_CUSTOMFORCE;
pub const LPCIMM_CUSTOMFORCE: u32 = LPCFEELIT_CUSTOMFORCE;

pub const LPIMM_ENUMDEVICESCALLBACK: u32 = LPFEELIT_ENUMDEVICESCALLBACK;

/* Effect Types */
pub const IMM_EFFECTTYPE_ALL: u32 = FEELIT_FEFFECTTYPE_ALL;

pub const IMM_EFFECTTYPE_CONSTANTFORCE: u32 = FEELIT_FEFFECTTYPE_CONSTANTFORCE;
pub const IMM_EFFECTTYPE_RAMPFORCE: u32 = FEELIT_FEFFECTTYPE_RAMPFORCE;
pub const IMM_EFFECTTYPE_PERIODIC: u32 = FEELIT_FEFFECTTYPE_PERIODIC;
pub const IMM_EFFECTTYPE_CONDITION: u32 = FEELIT_FEFFECTTYPE_CONDITION;
pub const IMM_EFFECTTYPE_ENCLOSURE: u32 = FEELIT_FEFFECTTYPE_ENCLOSURE;
pub const IMM_EFFECTTYPE_ELLIPSE: u32 = FEELIT_FEFFECTTYPE_ELLIPSE;
pub const IMM_EFFECTTYPE_TEXTURE: u32 = FEELIT_FEFFECTTYPE_TEXTURE;
pub const IMM_EFFECTTYPE_COMPOUND: u32 = 0x00000008;
pub const IMM_EFFECTTYPE_CUSTOMFORCE: u32 = FEELIT_FEFFECTTYPE_CUSTOMFORCE;
pub const IMM_EFFECTTYPE_HARDWARE: u32 = FEELIT_FEFFECTTYPE_HARDWARE;

pub const IMM_EFFECTTYPE_FFATTACK: u32 = FEELIT_FEFFECTTYPE_FFATTACK;
pub const IMM_EFFECTTYPE_FFFADE: u32 = FEELIT_FEFFECTTYPE_FFFADE;
pub const IMM_EFFECTTYPE_SATURATION: u32 = FEELIT_FEFFECTTYPE_SATURATION;
pub const IMM_EFFECTTYPE_POSNEGCOEFFICIENTS: u32 = FEELIT_FEFFECTTYPE_POSNEGCOEFFICIENTS;
pub const IMM_EFFECTTYPE_POSNEGSATURATION: u32 = FEELIT_FEFFECTTYPE_POSNEGSATURATION;
pub const IMM_EFFECTTYPE_DEADBAND: u32 = FEELIT_FEFFECTTYPE_DEADBAND;

/* Units */
pub const IMM_DEGREES: u32 = FEELIT_DEGREES;
pub const IMM_FFNOMINALMAX: u32 = FEELIT_FFNOMINALMAX;
pub const IMM_SECONDS: u32 = FEELIT_SECONDS;

/* Start Flags */
pub const IMM_START_SOLO: u32 = FEELIT_FSTART_SOLO;
pub const IMM_START_NODOWNLOAD: u32 = FEELIT_FSTART_NODOWNLOAD;

/* Status Flags */
pub const IMM_STATUS_PLAYING: u32 = FEELIT_FSTATUS_PLAYING;
pub const IMM_STATUS_EMULATED: u32 = FEELIT_FSTATUS_EMULATED;

/* Stiffness Mask Flags */
pub const IMM_STIFF_NONE: u32 = FEELIT_FSTIFF_NONE;
pub const IMM_STIFF_OUTERLEFTWALL: u32 = FEELIT_FSTIFF_OUTERLEFTWALL;
pub const IMM_STIFF_INNERLEFTWALL: u32 = FEELIT_FSTIFF_INNERLEFTWALL;
pub const IMM_STIFF_INNERRIGHTWALL: u32 = FEELIT_FSTIFF_INNERRIGHTWALL;
pub const IMM_STIFF_OUTERRIGHTWALL: u32 = FEELIT_FSTIFF_OUTERRIGHTWALL;
pub const IMM_STIFF_OUTERTOPWALL: u32 = FEELIT_FSTIFF_OUTERTOPWALL;
pub const IMM_STIFF_INNERTOPWALL: u32 = FEELIT_FSTIFF_INNERTOPWALL;
pub const IMM_STIFF_INNERBOTTOMWALL: u32 = FEELIT_FSTIFF_INNERBOTTOMWALL;
pub const IMM_STIFF_OUTERBOTTOMWALL: u32 = FEELIT_FSTIFF_OUTERBOTTOMWALL;
pub const IMM_STIFF_OUTERANYWALL: u32 = FEELIT_FSTIFF_OUTERANYWALL;
pub const IMM_STIFF_INBOUNDANYWALL: u32 = FEELIT_FSTIFF_INBOUNDANYWALL;
pub const IMM_STIFF_INNERANYWALL: u32 = FEELIT_FSTIFF_INNERANYWALL;
pub const IMM_STIFF_OUTBOUNDANYWALL: u32 = FEELIT_FSTIFF_OUTBOUNDANYWALL;
pub const IMM_STIFF_ANYWALL: u32 = FEELIT_FSTIFF_ANYWALL;

/* Clipping Mask Flags */
pub const IMM_CLIP_NONE: u32 = FEELIT_FCLIP_NONE;
pub const IMM_CLIP_OUTERLEFTWALL: u32 = FEELIT_FCLIP_OUTERLEFTWALL;
pub const IMM_CLIP_INNERLEFTWALL: u32 = FEELIT_FCLIP_INNERLEFTWALL;
pub const IMM_CLIP_INNERRIGHTWALL: u32 = FEELIT_FCLIP_INNERRIGHTWALL;
pub const IMM_CLIP_OUTERRIGHTWALL: u32 = FEELIT_FCLIP_OUTERRIGHTWALL;
pub const IMM_CLIP_OUTERTOPWALL: u32 = FEELIT_FCLIP_OUTERTOPWALL;
pub const IMM_CLIP_INNERTOPWALL: u32 = FEELIT_FCLIP_INNERTOPWALL;
pub const IMM_CLIP_INNERBOTTOMWALL: u32 = FEELIT_FCLIP_INNERBOTTOMWALL;
pub const IMM_CLIP_OUTERBOTTOMWALL: u32 = FEELIT_FCLIP_OUTERBOTTOMWALL;
pub const IMM_CLIP_OUTERANYWALL: u32 = FEELIT_FCLIP_OUTERANYWALL;
pub const IMM_CLIP_INNERANYWALL: u32 = FEELIT_FCLIP_INNERANYWALL;
pub const IMM_CLIP_ANYWALL: u32 = FEELIT_FCLIP_ANYWALL;

/* Device capabilities Stuct */
pub const IMM_DEVCAPS: u32 = FEELIT_DEVCAPS;
pub const LPIMM_DEVCAPS: u32 = LPFEELIT_DEVCAPS;
pub const LPCIMM_DEVCAPS: u32 = LPCFEELIT_DEVCAPS;

/* Device capabilities flags */
pub const IMM_DEVCAPS_ATTACHED: u32 = FEELIT_FDEVCAPS_ATTACHED;
pub const IMM_DEVCAPS_POLLEDDEVICE: u32 = FEELIT_FDEVCAPS_POLLEDDEVICE;
pub const IMM_DEVCAPS_EMULATED: u32 = FEELIT_FDEVCAPS_EMULATED;
pub const IMM_DEVCAPS_POLLEDDATAFORMAT: u32 = FEELIT_FDEVCAPS_POLLEDDATAFORMAT;
pub const IMM_DEVCAPS_FORCEFEEDBACK: u32 = FEELIT_FDEVCAPS_FORCEFEEDBACK;
pub const IMM_DEVCAPS_FFATTACK: u32 = FEELIT_FDEVCAPS_FFATTACK;
pub const IMM_DEVCAPS_FFFADE: u32 = FEELIT_FDEVCAPS_FFFADE;
pub const IMM_DEVCAPS_SATURATION: u32 = FEELIT_FDEVCAPS_SATURATION;
pub const IMM_DEVCAPS_POSNEGCOEFFICIENTS: u32 = FEELIT_FDEVCAPS_POSNEGCOEFFICIENTS;
pub const IMM_DEVCAPS_POSNEGSATURATION: u32 = FEELIT_FDEVCAPS_POSNEGSATURATION;
pub const IMM_DEVCAPS_DEADBAND: u32 = FEELIT_FDEVCAPS_DEADBAND;

pub const LPIMM_DEVICEINSTANCE: u32 = LPFEELIT_DEVICEINSTANCE;
pub const LPCIMM_DEVICEOBJECTINSTANCE: u32 = LPCFEELIT_DEVICEOBJECTINSTANCE;
pub const LPCIMM_EFFECTINFO: u32 = LPCFEELIT_EFFECTINFO;

pub const IMM_PARAM_DURATION: u32 = FEELIT_FPARAM_DURATION;
pub const IMM_PARAM_SAMPLEPERIOD: u32 = FEELIT_FPARAM_SAMPLEPERIOD;
pub const IMM_PARAM_GAIN: u32 = FEELIT_FPARAM_GAIN;
pub const IMM_PARAM_TRIGGERBUTTON: u32 = FEELIT_FPARAM_TRIGGERBUTTON;
pub const IMM_PARAM_TRIGGERREPEATINTERVAL: u32 = FEELIT_FPARAM_TRIGGERREPEATINTERVAL;
pub const IMM_PARAM_AXES: u32 = FEELIT_FPARAM_AXES;
pub const IMM_PARAM_DIRECTION: u32 = FEELIT_FPARAM_DIRECTION;
pub const IMM_PARAM_ENVELOPE: u32 = FEELIT_FPARAM_ENVELOPE;
pub const IMM_PARAM_TYPESPECIFICPARAMS: u32 = FEELIT_FPARAM_TYPESPECIFICPARAMS;
pub const IMM_PARAM_STARTDELAY: u32 = FEELIT_FPARAM_STARTDELAY;
pub const IMM_PARAM_ALLPARAMS: u32 = FEELIT_FPARAM_ALLPARAMS;
pub const IMM_PARAM_START: u32 = FEELIT_FPARAM_START;
pub const IMM_PARAM_NORESTART: u32 = FEELIT_FPARAM_NORESTART;
pub const IMM_PARAM_NODOWNLOAD: u32 = FEELIT_FPARAM_NODOWNLOAD;

pub const IMM_EFFECT_OBJECTIDS: u32 = FEELIT_FEFFECT_OBJECTIDS;
pub const IMM_EFFECT_OBJECTOFFSETS: u32 = FEELIT_FEFFECT_OBJECTOFFSETS;
pub const IMM_EFFECT_CARTESIAN: u32 = FEELIT_FEFFECT_CARTESIAN;
pub const IMM_EFFECT_POLAR: u32 = FEELIT_FEFFECT_POLAR;
pub const IMM_EFFECT_SPHERICAL: u32 = FEELIT_FEFFECT_SPHERICAL;

pub const IMM_PARAM_NOTRIGGER: u32 = FEELIT_PARAM_NOTRIGGER;

/* Offsets */
pub const IMM_MOUSEOFFSET_XAXIS: u32 = FEELIT_MOUSEOFFSET_XAXIS;
pub const IMM_MOUSEOFFSET_YAXIS: u32 = FEELIT_MOUSEOFFSET_YAXIS;
pub const IMM_MOUSEOFFSET_ZAXIS: u32 = FEELIT_MOUSEOFFSET_ZAXIS;
pub const IMM_MOUSEOFFSET_XFORCE: u32 = FEELIT_MOUSEOFFSET_XFORCE;
pub const IMM_MOUSEOFFSET_YFORCE: u32 = FEELIT_MOUSEOFFSET_YFORCE;
pub const IMM_MOUSEOFFSET_ZFORCE: u32 = FEELIT_MOUSEOFFSET_ZFORCE;
pub const IMM_MOUSEOFFSET_BUTTON0: u32 = FEELIT_MOUSEOFFSET_BUTTON0;
pub const IMM_MOUSEOFFSET_BUTTON1: u32 = FEELIT_MOUSEOFFSET_BUTTON1;
pub const IMM_MOUSEOFFSET_BUTTON2: u32 = FEELIT_MOUSEOFFSET_BUTTON2;
pub const IMM_MOUSEOFFSET_BUTTON3: u32 = FEELIT_MOUSEOFFSET_BUTTON3;

/* Cooperative Level Flags */
pub const IMM_COOPLEVEL_FOREGROUND: u32 = FEELIT_FCOOPLEVEL_FOREGROUND;
pub const IMM_COOPLEVEL_BACKGROUND: u32 = FEELIT_FCOOPLEVEL_BACKGROUND;

/* Enumeration codes */
pub const IMM_ENUM_STOP: u32 = FEELIT_ENUM_STOP;
pub const IMM_ENUM_CONTINUE: u32 = FEELIT_ENUM_CONTINUE;

pub const IMM_ENUMDEV_ALLDEVICES: u32 = FEELIT_FENUMDEV_ALLDEVICES;
pub const IMM_ENUMDEV_ATTACHEDONLY: u32 = FEELIT_FENUMDEV_ATTACHEDONLY;
pub const IMM_ENUMDEV_FORCEFEEDBACK: u32 = FEELIT_FENUMDEV_FORCEFEEDBACK;

/* Return values */
pub const IMM_RESULT_OK: u32 = FEELIT_RESULT_OK;
pub const IMM_RESULT_NOTATTACHED: u32 = FEELIT_RESULT_NOTATTACHED;
pub const IMM_RESULT_BUFFEROVERFLOW: u32 = FEELIT_RESULT_BUFFEROVERFLOW;
pub const IMM_RESULT_PROPNOEFFECT: u32 = FEELIT_RESULT_PROPNOEFFECT;
pub const IMM_RESULT_NOEFFECT: u32 = FEELIT_RESULT_NOEFFECT;
pub const IMM_RESULT_POLLEDDEVICE: u32 = FEELIT_RESULT_POLLEDDEVICE;
pub const IMM_RESULT_DOWNLOADSKIPPED: u32 = FEELIT_RESULT_DOWNLOADSKIPPED;
pub const IMM_RESULT_EFFECTRESTARTED: u32 = FEELIT_RESULT_EFFECTRESTARTED;
pub const IMM_RESULT_TRUNCATED: u32 = FEELIT_RESULT_TRUNCATED;
pub const IMM_RESULT_TRUNCATEDANDRESTARTED: u32 = FEELIT_RESULT_TRUNCATEDANDRESTARTED;
pub const IMM_ERROR_OLDFEELITVERSION: u32 = FEELIT_ERROR_OLDFEELITVERSION;
pub const IMM_ERROR_BETAFEELITVERSION: u32 = FEELIT_ERROR_BETAFEELITVERSION;
pub const IMM_ERROR_BADDRIVERVER: u32 = FEELIT_ERROR_BADDRIVERVER;
pub const IMM_ERROR_DEVICENOTREG: u32 = FEELIT_ERROR_DEVICENOTREG;
pub const IMM_ERROR_NOTFOUND: u32 = FEELIT_ERROR_NOTFOUND;
pub const IMM_ERROR_OBJECTNOTFOUND: u32 = FEELIT_ERROR_OBJECTNOTFOUND;
pub const IMM_ERROR_INVALIDPARAM: u32 = FEELIT_ERROR_INVALIDPARAM;
pub const IMM_ERROR_NOINTERFACE: u32 = FEELIT_ERROR_NOINTERFACE;
pub const IMM_ERROR_GENERIC: u32 = FEELIT_ERROR_GENERIC;
pub const IMM_ERROR_OUTOFMEMORY: u32 = FEELIT_ERROR_OUTOFMEMORY;
pub const IMM_ERROR_UNSUPPORTED: u32 = FEELIT_ERROR_UNSUPPORTED;
pub const IMM_ERROR_NOTINITIALIZED: u32 = FEELIT_ERROR_NOTINITIALIZED;
pub const IMM_ERROR_ALREADYINITIALIZED: u32 = FEELIT_ERROR_ALREADYINITIALIZED;
pub const IMM_ERROR_NOAGGREGATION: u32 = FEELIT_ERROR_NOAGGREGATION;
pub const IMM_ERROR_OTHERAPPHASPRIO: u32 = FEELIT_ERROR_OTHERAPPHASPRIO;
pub const IMM_ERROR_INPUTLOST: u32 = FEELIT_ERROR_INPUTLOST;
pub const IMM_ERROR_ACQUIRED: u32 = FEELIT_ERROR_ACQUIRED;
pub const IMM_ERROR_NOTACQUIRED: u32 = FEELIT_ERROR_NOTACQUIRED;
pub const IMM_ERROR_READONLY: u32 = FEELIT_ERROR_READONLY;
pub const IMM_ERROR_HANDLEEXISTS: u32 = FEELIT_ERROR_HANDLEEXISTS;
pub const IMM_ERROR_INSUFFICIENTPRIVS: u32 = FEELIT_ERROR_INSUFFICIENTPRIVS;
pub const IMM_ERROR_DEVICEFULL: u32 = FEELIT_ERROR_DEVICEFULL;
pub const IMM_ERROR_MOREDATA: u32 = FEELIT_ERROR_MOREDATA;
pub const IMM_ERROR_NOTDOWNLOADED: u32 = FEELIT_ERROR_NOTDOWNLOADED;
pub const IMM_ERROR_HASEFFECTS: u32 = FEELIT_ERROR_HASEFFECTS;
pub const IMM_ERROR_NOTEXCLUSIVEACQUIRED: u32 = FEELIT_ERROR_NOTEXCLUSIVEACQUIRED;
pub const IMM_ERROR_INCOMPLETEEFFECT: u32 = FEELIT_ERROR_INCOMPLETEEFFECT;
pub const IMM_ERROR_NOTBUFFERED: u32 = FEELIT_ERROR_NOTBUFFERED;
pub const IMM_ERROR_EFFECTPLAYING: u32 = FEELIT_ERROR_EFFECTPLAYING;
pub const IMM_ERROR_INTERNAL: u32 = FEELIT_ERROR_INTERNAL;
pub const IMM_ERROR_INACTIVE: u32 = FEELIT_ERROR_INACTIVE;

//================================================================
// GUID WRAPPERS
//================================================================

//
// Immersion --> Feelit Wrappers
//
pub const GUID_Imm_ConstantForce: u32 = GUID_Feelit_ConstantForce;
pub const GUID_Imm_RampForce: u32 = GUID_Feelit_RampForce;
pub const GUID_Imm_Square: u32 = GUID_Feelit_Square;
pub const GUID_Imm_Sine: u32 = GUID_Feelit_Sine;
pub const GUID_Imm_Triangle: u32 = GUID_Feelit_Triangle;
pub const GUID_Imm_SawtoothUp: u32 = GUID_Feelit_SawtoothUp;
pub const GUID_Imm_SawtoothDown: u32 = GUID_Feelit_SawtoothDown;
pub const GUID_Imm_Spring: u32 = GUID_Feelit_Spring;
pub const GUID_Imm_DeviceSpring: u32 = GUID_Feelit_DeviceSpring;
pub const GUID_Imm_Damper: u32 = GUID_Feelit_Damper;
pub const GUID_Imm_Inertia: u32 = GUID_Feelit_Inertia;
pub const GUID_Imm_Friction: u32 = GUID_Feelit_Friction;
pub const GUID_Imm_Texture: u32 = GUID_Feelit_Texture;
pub const GUID_Imm_Grid: u32 = GUID_Feelit_Grid;
pub const GUID_Imm_Enclosure: u32 = GUID_Feelit_Enclosure;
pub const GUID_Imm_Ellipse: u32 = GUID_Feelit_Ellipse;
pub const GUID_Imm_CustomForce: u32 = GUID_Feelit_CustomForce;

pub const CLSID_Imm: u32 = CLSID_Feelit;
pub const CLSID_ImmDevice: u32 = CLSID_FeelitDevice;
pub const GUID_Imm_XAxis: u32 = GUID_Feelit_XAxis;
pub const GUID_Imm_YAxis: u32 = GUID_Feelit_YAxis;
pub const GUID_Imm_ZAxis: u32 = GUID_Feelit_ZAxis;
pub const GUID_Imm_RxAxis: u32 = GUID_Feelit_RxAxis;
pub const GUID_Imm_RyAxis: u32 = GUID_Feelit_RyAxis;
pub const GUID_Imm_RzAxis: u32 = GUID_Feelit_RzAxis;
pub const GUID_Imm_Slider: u32 = GUID_Feelit_Slider;
pub const GUID_Imm_Button: u32 = GUID_Feelit_Button;
pub const GUID_Imm_Key: u32 = GUID_Feelit_Key;
pub const GUID_Imm_POV: u32 = GUID_Feelit_POV;
pub const GUID_Imm_Unknown: u32 = GUID_Feelit_Unknown;
pub const GUID_Imm_Mouse: u32 = GUID_Feelit_Mouse;
