// GENERATED trimmed module for `code/game` — do not edit by hand.

#[path = "../../../../../src/code/game/ai_h.rs"]
pub mod ai_h;
#[path = "../../../../../src/code/game/b_local_h.rs"]
pub mod b_local_h;
#[path = "../../../../../src/code/game/b_public_h.rs"]
pub mod b_public_h;
#[path = "../../../../../src/code/game/bg_public_h.rs"]
pub mod bg_public_h;
#[path = "../../../../../src/code/game/bset_h.rs"]
pub mod bset_h;
#[path = "../../../../../src/code/game/bstate_h.rs"]
pub mod bstate_h;
#[path = "../../../../../src/code/game/g_items_h.rs"]
pub mod g_items_h;
#[path = "../../../../../src/code/game/g_local_h.rs"]
pub mod g_local_h;
#[path = "../../../../../src/code/game/g_public_h.rs"]
pub mod g_public_h;
#[path = "../../../../../src/code/game/g_shared_h.rs"]
pub mod g_shared_h;
#[path = "../../../../../src/code/game/g_vehicles_h.rs"]
pub mod g_vehicles_h;
#[path = "../../../../../src/code/game/ghoul2_shared_h.rs"]
pub mod ghoul2_shared_h;
#[path = "../../../../../src/code/game/hitlocs_h.rs"]
pub mod hitlocs_h;
#[path = "../../../../../src/code/game/mod.rs"]
pub mod mod;
#[path = "../../../../../src/code/game/objectives_h.rs"]
pub mod objectives_h;
#[path = "../../../../../src/code/game/q_shared.rs"]
pub mod q_shared;
#[path = "../../../../../src/code/game/say_h.rs"]
pub mod say_h;
#[path = "../../../../../src/code/game/statindex_h.rs"]
pub mod statindex_h;
#[path = "../../../../../src/code/game/surfaceflags_h.rs"]
pub mod surfaceflags_h;
#[path = "../../../../../src/code/game/teams_h.rs"]
pub mod teams_h;
#[path = "../../../../../src/code/game/weapons_h.rs"]
pub mod weapons_h;
