// GENERATED trimmed module for `codemp/game` — do not edit by hand.

#[path = "../../../../../src/codemp/game/ai_h.rs"]
pub mod ai_h;
#[path = "../../../../../src/codemp/game/ai_main.rs"]
pub mod ai_main;
#[path = "../../../../../src/codemp/game/ai_main_h.rs"]
pub mod ai_main_h;
#[path = "../../../../../src/codemp/game/ai_util.rs"]
pub mod ai_util;
#[path = "../../../../../src/codemp/game/ai_wpnav.rs"]
pub mod ai_wpnav;
#[path = "../../../../../src/codemp/game/animalnpc.rs"]
pub mod animalnpc;
#[path = "../../../../../src/codemp/game/anims.rs"]
pub mod anims;
#[path = "../../../../../src/codemp/game/b_local_h.rs"]
pub mod b_local_h;
#[path = "../../../../../src/codemp/game/b_public_h.rs"]
pub mod b_public_h;
#[path = "../../../../../src/codemp/game/be_aas_h.rs"]
pub mod be_aas_h;
#[path = "../../../../../src/codemp/game/bg_g2_utils.rs"]
pub mod bg_g2_utils;
#[path = "../../../../../src/codemp/game/bg_lib.rs"]
pub mod bg_lib;
#[path = "../../../../../src/codemp/game/bg_local_h.rs"]
pub mod bg_local_h;
#[path = "../../../../../src/codemp/game/bg_misc.rs"]
pub mod bg_misc;
#[path = "../../../../../src/codemp/game/bg_panimate.rs"]
pub mod bg_panimate;
#[path = "../../../../../src/codemp/game/bg_pmove.rs"]
pub mod bg_pmove;
#[path = "../../../../../src/codemp/game/bg_public.rs"]
pub mod bg_public;
#[path = "../../../../../src/codemp/game/bg_saber.rs"]
pub mod bg_saber;
#[path = "../../../../../src/codemp/game/bg_saberLoad.rs"]
pub mod bg_saberLoad;
#[path = "../../../../../src/codemp/game/bg_saga.rs"]
pub mod bg_saga;
#[path = "../../../../../src/codemp/game/bg_saga_h.rs"]
pub mod bg_saga_h;
#[path = "../../../../../src/codemp/game/bg_slidemove.rs"]
pub mod bg_slidemove;
#[path = "../../../../../src/codemp/game/bg_vehicleLoad.rs"]
pub mod bg_vehicleLoad;
#[path = "../../../../../src/codemp/game/bg_vehicles_h.rs"]
pub mod bg_vehicles_h;
#[path = "../../../../../src/codemp/game/bg_weapons.rs"]
pub mod bg_weapons;
#[path = "../../../../../src/codemp/game/bg_weapons_h.rs"]
pub mod bg_weapons_h;
#[path = "../../../../../src/codemp/game/botlib_h.rs"]
pub mod botlib_h;
#[path = "../../../../../src/codemp/game/fighternpc.rs"]
pub mod fighternpc;
#[path = "../../../../../src/codemp/game/g_ICARUScb.rs"]
pub mod g_ICARUScb;
#[path = "../../../../../src/codemp/game/g_active.rs"]
pub mod g_active;
#[path = "../../../../../src/codemp/game/g_bot.rs"]
pub mod g_bot;
#[path = "../../../../../src/codemp/game/g_client.rs"]
pub mod g_client;
#[path = "../../../../../src/codemp/game/g_cmds.rs"]
pub mod g_cmds;
#[path = "../../../../../src/codemp/game/g_combat.rs"]
pub mod g_combat;
#[path = "../../../../../src/codemp/game/g_exphysics.rs"]
pub mod g_exphysics;
#[path = "../../../../../src/codemp/game/g_items.rs"]
pub mod g_items;
#[path = "../../../../../src/codemp/game/g_local.rs"]
pub mod g_local;
#[path = "../../../../../src/codemp/game/g_log.rs"]
pub mod g_log;
#[path = "../../../../../src/codemp/game/g_main.rs"]
pub mod g_main;
#[path = "../../../../../src/codemp/game/g_mem.rs"]
pub mod g_mem;
#[path = "../../../../../src/codemp/game/g_misc.rs"]
pub mod g_misc;
#[path = "../../../../../src/codemp/game/g_missile.rs"]
pub mod g_missile;
#[path = "../../../../../src/codemp/game/g_mover.rs"]
pub mod g_mover;
#[path = "../../../../../src/codemp/game/g_nav.rs"]
pub mod g_nav;
#[path = "../../../../../src/codemp/game/g_navnew.rs"]
pub mod g_navnew;
#[path = "../../../../../src/codemp/game/g_object.rs"]
pub mod g_object;
#[path = "../../../../../src/codemp/game/g_public_h.rs"]
pub mod g_public_h;
#[path = "../../../../../src/codemp/game/g_saga.rs"]
pub mod g_saga;
#[path = "../../../../../src/codemp/game/g_session.rs"]
pub mod g_session;
#[path = "../../../../../src/codemp/game/g_spawn.rs"]
pub mod g_spawn;
#[path = "../../../../../src/codemp/game/g_svcmds.rs"]
pub mod g_svcmds;
#[path = "../../../../../src/codemp/game/g_target.rs"]
pub mod g_target;
#[path = "../../../../../src/codemp/game/g_team.rs"]
pub mod g_team;
#[path = "../../../../../src/codemp/game/g_timer.rs"]
pub mod g_timer;
#[path = "../../../../../src/codemp/game/g_trigger.rs"]
pub mod g_trigger;
#[path = "../../../../../src/codemp/game/g_turret.rs"]
pub mod g_turret;
#[path = "../../../../../src/codemp/game/g_turret_g2.rs"]
pub mod g_turret_g2;
#[path = "../../../../../src/codemp/game/g_utils.rs"]
pub mod g_utils;
#[path = "../../../../../src/codemp/game/g_vehicleTurret.rs"]
pub mod g_vehicleTurret;
#[path = "../../../../../src/codemp/game/g_vehicles.rs"]
pub mod g_vehicles;
#[path = "../../../../../src/codemp/game/g_weapon.rs"]
pub mod g_weapon;
#[path = "../../../../../src/codemp/game/mod.rs"]
pub mod mod;
#[path = "../../../../../src/codemp/game/npc.rs"]
pub mod npc;
#[path = "../../../../../src/codemp/game/npc_ai_atst.rs"]
pub mod npc_ai_atst;
#[path = "../../../../../src/codemp/game/npc_ai_default.rs"]
pub mod npc_ai_default;
#[path = "../../../../../src/codemp/game/npc_ai_droid.rs"]
pub mod npc_ai_droid;
#[path = "../../../../../src/codemp/game/npc_ai_galakmech.rs"]
pub mod npc_ai_galakmech;
#[path = "../../../../../src/codemp/game/npc_ai_grenadier.rs"]
pub mod npc_ai_grenadier;
#[path = "../../../../../src/codemp/game/npc_ai_howler.rs"]
pub mod npc_ai_howler;
#[path = "../../../../../src/codemp/game/npc_ai_imperialprobe.rs"]
pub mod npc_ai_imperialprobe;
#[path = "../../../../../src/codemp/game/npc_ai_interrogator.rs"]
pub mod npc_ai_interrogator;
#[path = "../../../../../src/codemp/game/npc_ai_jedi.rs"]
pub mod npc_ai_jedi;
#[path = "../../../../../src/codemp/game/npc_ai_mark1.rs"]
pub mod npc_ai_mark1;
#[path = "../../../../../src/codemp/game/npc_ai_mark2.rs"]
pub mod npc_ai_mark2;
#[path = "../../../../../src/codemp/game/npc_ai_minemonster.rs"]
pub mod npc_ai_minemonster;
#[path = "../../../../../src/codemp/game/npc_ai_rancor.rs"]
pub mod npc_ai_rancor;
#[path = "../../../../../src/codemp/game/npc_ai_remote.rs"]
pub mod npc_ai_remote;
#[path = "../../../../../src/codemp/game/npc_ai_seeker.rs"]
pub mod npc_ai_seeker;
#[path = "../../../../../src/codemp/game/npc_ai_sentry.rs"]
pub mod npc_ai_sentry;
#[path = "../../../../../src/codemp/game/npc_ai_sniper.rs"]
pub mod npc_ai_sniper;
#[path = "../../../../../src/codemp/game/npc_ai_stormtrooper.rs"]
pub mod npc_ai_stormtrooper;
#[path = "../../../../../src/codemp/game/npc_ai_utils.rs"]
pub mod npc_ai_utils;
#[path = "../../../../../src/codemp/game/npc_ai_wampa.rs"]
pub mod npc_ai_wampa;
#[path = "../../../../../src/codemp/game/npc_behavior.rs"]
pub mod npc_behavior;
#[path = "../../../../../src/codemp/game/npc_combat.rs"]
pub mod npc_combat;
#[path = "../../../../../src/codemp/game/npc_goal.rs"]
pub mod npc_goal;
#[path = "../../../../../src/codemp/game/npc_misc.rs"]
pub mod npc_misc;
#[path = "../../../../../src/codemp/game/npc_move.rs"]
pub mod npc_move;
#[path = "../../../../../src/codemp/game/npc_reactions.rs"]
pub mod npc_reactions;
#[path = "../../../../../src/codemp/game/npc_senses.rs"]
pub mod npc_senses;
#[path = "../../../../../src/codemp/game/npc_sounds.rs"]
pub mod npc_sounds;
#[path = "../../../../../src/codemp/game/npc_spawn.rs"]
pub mod npc_spawn;
#[path = "../../../../../src/codemp/game/npc_stats.rs"]
pub mod npc_stats;
#[path = "../../../../../src/codemp/game/npc_utils.rs"]
pub mod npc_utils;
#[path = "../../../../../src/codemp/game/q_math.rs"]
pub mod q_math;
#[path = "../../../../../src/codemp/game/q_shared.rs"]
pub mod q_shared;
#[path = "../../../../../src/codemp/game/q_shared_h.rs"]
pub mod q_shared_h;
#[path = "../../../../../src/codemp/game/speedernpc.rs"]
pub mod speedernpc;
#[path = "../../../../../src/codemp/game/surfaceflags_h.rs"]
pub mod surfaceflags_h;
#[path = "../../../../../src/codemp/game/teams_h.rs"]
pub mod teams_h;
#[path = "../../../../../src/codemp/game/tri_coll_test.rs"]
pub mod tri_coll_test;
#[path = "../../../../../src/codemp/game/w_force.rs"]
pub mod w_force;
#[path = "../../../../../src/codemp/game/w_saber.rs"]
pub mod w_saber;
#[path = "../../../../../src/codemp/game/w_saber_h.rs"]
pub mod w_saber_h;
#[path = "../../../../../src/codemp/game/walkernpc.rs"]
pub mod walkernpc;
